### ISSUE TITLE
Request for Linux version

### ISSUE THREAD

**Issue by chowdhuryahmedhossain** [Abdus-Samee/RunApps#1]
Can you add support for Ubuntu?

**Comment by Abdus-Samee** [comment]
I haven't worked with Ubuntu, but as far as I know, the program doesn't have any OS dependencies except for the usage of the os module and the opening of file dialog, which I don't know if they are OS-specific or not. I believe the program runs fine in windows and mac, so it should in ubuntu unless the aforementioned reasons interrupt.
